CREATE TABLE userdetails(
   Id  int NOT NULL AUTO_INCREMENT,
   FullNameOfTheApplicant varchar(45) DEFAULT NULL,
   DOB varchar(45) DEFAULT NULL,
   TypeOfApplicant varchar(45) DEFAULT NULL,
   MobileNo varchar(45) DEFAULT NULL,
   Email varchar(45) DEFAULT NULL,
   HouseNo varchar(45) DEFAULT NULL,
   District varchar(45) DEFAULT NULL,
   PoliceStation varchar(45) DEFAULT NULL,
   PinCode varchar(45) DEFAULT NULL,
   LandMark varchar(45) DEFAULT NULL,
   Teshil varchar(45) DEFAULT NULL,
   PostOffice varchar(45) DEFAULT NULL,
   VehicleRegistrationNo varchar(45) DEFAULT NULL,
   VehicleType varchar(45) DEFAULT NULL,
   JourneyType varchar(45) DEFAULT NULL,
   PassFromDate varchar(45) DEFAULT NULL,
   PassToDate varchar(45) DEFAULT NULL,
   PurposeOfTravel varchar(45) DEFAULT NULL,
   FromLocation varchar(45) DEFAULT NULL,
   ToLocation varchar(45) DEFAULT NULL,
   Remarks varchar(45) DEFAULT NULL,
   Name1 varchar(45) DEFAULT NULL,
   Age1 varchar(45) DEFAULT NULL,
   MobileNo1 varchar(45) DEFAULT NULL,
   Name2 varchar(45) DEFAULT NULL,
   Age2  varchar(45) DEFAULT NULL,
   MobileNo2 varchar(45) DEFAULT NULL,
   Name3  varchar(45) DEFAULT NULL,
   Age3 varchar(45) DEFAULT NULL,
   MobileNo3 varchar(45) DEFAULT NULL,
   Name4 varchar(45) DEFAULT NULL,
   Age4 varchar(45) DEFAULT NULL,
   MobileNo4 varchar(45) DEFAULT NULL,
  PRIMARY KEY (Id)
);


ALTER TABLE userdetails ADD epassStatus varchar(45);